[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Projects"
weight = 200
identifier = "projects"
url = "/projects/"

[[main]]
name = "Skills"
weight = 300
identifier = "skills"
url = "/skills/"